[server]
host = "0.0.0.0"
port = 8877

[auth]
jwt_secret = "your-secret-key-change-in-production"
token_ttl_seconds = 60

# 硬编码用户列表 (生产环境应使用数据库)
[[auth.users]]
username = "admin"
password = "admin123"
quota_tier = "premium"  # 高级版 1500次/月
is_active = true

[[auth.users]]
username = "user1"
password = "pass123"
quota_tier = "basic"  # 基础版 500次/月
is_active = true

[[auth.users]]
username = "user2"
password = "pass456"
quota_tier = "pro"  # 专业版 1000次/月
is_active = true

[deepseek]
# 从环境变量 OPENAI_API_KEY 读取
api_key = ""
base_url = "https://api.deepseek.com/v1"
timeout_seconds = 60

# HTTP客户端性能配置
[deepseek.http_client]
# 连接池配置
pool_max_idle_per_host = 20      # 每个主机最大空闲连接数
pool_idle_timeout_seconds = 90   # 连接保活时间(秒)

# 超时配置  
connect_timeout_seconds = 10     # TCP连接建立超时

# TCP优化
tcp_nodelay = true              # 禁用Nagle算法，降低延迟
http2_adaptive_window = true    # HTTP/2自适应窗口

[rate_limit]
requests_per_second = 2
queue_capacity = 20
queue_timeout_seconds = 5

[quota]
save_interval = 100  # 每100次请求写一次磁盘
monthly_reset_day = 1  # 每月1号重置
