[auth]
jwt_secret = "your-secret-key-change-in-production"
token_ttl_seconds = 60

# 用户配置存储在 data/users/ 目录（每个用户一个 .toml 文件）
# 支持动态修改，无需重启服务
# 如果需要添加初始用户，可以在这里定义 [[auth.users]]，服务首次启动时会自动导入

[deepseek]
api_key = ""
base_url = "https://api.deepseek.com/v1"
timeout_seconds = 60

[deepseek.http_client]
connect_timeout_seconds = 10
http2_adaptive_window = true
pool_idle_timeout_seconds = 90
pool_max_idle_per_host = 20
tcp_nodelay = true

[quota]
monthly_reset_day = 1
save_interval = 5

[quota.tiers]
basic = 500
premium = 1500
pro = 1000

[rate_limit]
queue_capacity = 20
queue_timeout_seconds = 5
requests_per_second = 2

[server]
host = "0.0.0.0"
port = 8877
