[server]
host = "0.0.0.0"
port = 8080

[auth]
jwt_secret = "your-secret-key-change-in-production"
token_ttl_seconds = 3600

# 硬编码用户列表 (生产环境应使用数据库)
[[auth.users]]
username = "admin"
password = "admin123"

[[auth.users]]
username = "user1"
password = "pass123"

[glm]
# 从环境变量读取,默认值仅用于示例
api_key = ""
base_url = "https://open.bigmodel.cn/api/paas/v4"
timeout_seconds = 20

[rate_limit]
requests_per_second = 2
queue_capacity = 20
queue_timeout_seconds = 5
